### ISSUE TITLE
Document Apache Kudu binary compatibility with RedHat & Debian

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#12]
The goal is to check whether this project provides binary releases which can be used as-is on RedHat/CentOS and Debian machines.

If not we'll need to implement a build-pipeline.

The result of where the binaries can be found, what they contain (if there's anything special) and what works and doesn't work out of the box should be documented in a file in this repository somewhere.

**Comment by timrobertson100** [comment]
My understanding is that you'll need to make the Kudu build-pipeline.

The project only publishes source code releases but [the instructions](https://kudu.apache.org/docs/installation.html) show how to build for "RHEL 6, RHEL 7, RHEL 8, CentOS 6, CentOS 7, CentOS 8, Ubuntu 14.04 (trusty), Ubuntu 16.04 (xenial), Ubuntu 18.04 (bionic), Debian 8 (Jessie), or SLES 12."

Cloudera used to have a repository with [binaries](https://docs.cloudera.com/documentation/enterprise/5-14-x/topics/kudu_install_cli.html) but since [CDH 6.3.3](https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/kudu_install_upgrade_intro.html) you need Enterprise Support Subscription to access archive.cloudera.com.

I hope this helps.

**Comment by lfrancke** [comment]
Great, thank you Tim.

**Comment by timrobertson100** [comment]
[A proposal](https://mail-archives.apache.org/mod_mbox/kudu-user/202011.mbox/browser) on the `users@kudu` suggests making some changes that may be of interest (repeated here):

```
   1. Drop operating systems that are at or near EOL
      - Drop CentOS 6/RHEL 6 - EOL November 30th, 2020
      - Drop Ubuntu 14 (Trusty) - EOL April 30, 2019
      - Drop Ubuntu 16 (Xenial) - EOL April 30th, 2021
         - Note: The next Apache Kudu release would likely be early 2021
      - Drop Debian 8 (Jessie) - EOL June 30, 2020
      - A deprecation was noted for some all but Ubuntu 16 in the Kudu
      1.12.0 release notes:
      https://kudu.apache.org/releases/1.12.0/docs/release_notes.html#rn_1.12.0_obsoletions
      - We can and will still accept patches for fixes, but shouldn't
      document/promise support.
   2. Drop operating systems that are not well tested by the community
      - Drop SLES 12
      - Drop OS X 10.10 Yosemite, OS X 10.11 El Capitan, macOS Sierra
      - We can and will still accept patches for fixes, but shouldn't
      document/promise support.
   3. Add new operating system versions
      - Add Ubuntu 20.04 (Focal)
      - Add macOS 10.14 (Mojave), macOS 10.15 (Catalina), macOS 11 (Big Sur)
      4. Continued Innovation/Improvements
      - Bump C++ language level to C++17 (gcc 7)
         - Similar to CentOS/RHEL 6 current;y, devtoolset-7 will be used on
         Centos/RHEL 7 get gcc 7.3
         - This is aligned with the Apache Impala community requirements
      - Upgrade dependencies the required C++14 and higher
      - Introduce new dependencies that require or benefit from C++14 and
      higher
```
