### ISSUE TITLE
Add section of "Definition of Done" to our Contributor's guide

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#195]
This should go into our contributor's guide:

- Code contains useful comments
- (Integration-)Test cases added (or not applicable)
- Documentation added (or not applicable)
- Changelog updated (or not applicable)
- Cargo.toml only contains references to git tags (not specific commits or branches)
- Helm chart can be installed and deployed operator works (or not applicable)
- Examples have been added or updated
- Feature Tracker has been updated

**Comment by fhennig** [comment]
I think this list is mostly what's inside the review checklist in pull request templates, and I think it's good to have the list there and also maintain the list there as the source of truth. I have referenced this list in the [pull request guidelines](https://docs.stackable.tech/home/nightly/contributor/#contributing-workflow) and I think it makes sense to not explicitly duplicate the list into the docs.

So I would suggest we close this issue here? Maybe the formulations in the docs can be changed slightly, to make things clearer

**Comment by lfrancke** [comment]
Makes sense!
